/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние сервиса
         * @description Возвращает состояние и режим работы.
         *
         *     Провайдер AI и адаптер площадки показаны намеренно: по ответу должно быть
         *     сразу видно, работает ли стенд на заглушках. Иначе легко принять
         *     сгенерированный заглушкой результат за вывод настоящей модели.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список проектов */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Создать проект */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проект */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экономика проекта и производные метрики */
        get: operations["get_economics_api_v1_projects__project_id__economics_get"];
        /** Сохранить экономику проекта */
        put: operations["update_economics_api_v1_projects__project_id__economics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Availability
         * @description Насколько можно доверять значению.
         *
         *     Совпадает с состояниями карточки KPI в интерфейсе — одно и то же понятие не
         *     должно называться по-разному на разных концах системы.
         * @enum {string}
         */
        Availability: "available" | "proxy" | "unavailable";
        /**
         * EconomicsMode
         * @description Полнота экономики (v0.4 §5).
         * @enum {string}
         */
        EconomicsMode: "complete" | "limited" | "insufficient";
        /** EconomicsRead */
        EconomicsRead: {
            /** Average Order Value */
            average_order_value: string | null;
            /** Expected Value */
            expected_value: string | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate: string | null;
            main_conversion: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent: string | null;
            /** Monthly Budget */
            monthly_budget: string | null;
            /** Target Cac */
            target_cac: string | null;
            /** Target Cpl */
            target_cpl: string | null;
            /** Target Marketing Share */
            target_marketing_share: string | null;
            /** Version */
            version: number;
        };
        /**
         * EconomicsResponse
         * @description Ответ экономики: введённые данные и производные величины отдельно.
         *
         *     Разделение намеренное — интерфейс обязан отличать данные от вывода системы
         *     (v0.3 §140).
         */
        EconomicsResponse: {
            input: components["schemas"]["EconomicsRead"] | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            summary: components["schemas"]["EconomicsSummaryRead"];
        };
        /** EconomicsSummaryRead */
        EconomicsSummaryRead: {
            break_even_cac: components["schemas"]["MetricRead"];
            break_even_cpl: components["schemas"]["MetricRead"];
            break_even_roas: components["schemas"]["MetricRead"];
            /** Can Optimize By Sales */
            can_optimize_by_sales: boolean;
            /** Cta */
            cta: string | null;
            gross_profit_per_sale: components["schemas"]["MetricRead"];
            /** Missing Recommended */
            missing_recommended: string[];
            /** Missing Required */
            missing_required: string[];
            mode: components["schemas"]["EconomicsMode"];
            monthly_leads_capacity: components["schemas"]["MetricRead"];
            monthly_sales_capacity: components["schemas"]["MetricRead"];
            projected_gross_profit: components["schemas"]["MetricRead"];
            projected_revenue: components["schemas"]["MetricRead"];
            target_cac: components["schemas"]["MetricRead"];
            target_cpl: components["schemas"]["MetricRead"];
            target_roas: components["schemas"]["MetricRead"];
        };
        /**
         * EconomicsUpdate
         * @description Ввод экономики.
         *
         *     Все поля необязательные: проект не блокируется из-за незаполненной экономики
         *     (v0.4 §5). Полнота оценивается расчётом, а не валидацией запроса.
         */
        EconomicsUpdate: {
            /** Average Order Value */
            average_order_value?: number | string | null;
            /** Expected Value */
            expected_value?: number | string | null;
            /** Expected Version */
            expected_version?: number | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate?: number | string | null;
            main_conversion?: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent?: number | string | null;
            /** Monthly Budget */
            monthly_budget?: number | string | null;
            /** Target Cac */
            target_cac?: number | string | null;
            /** Target Cpl */
            target_cpl?: number | string | null;
            /** Target Marketing Share */
            target_marketing_share?: number | string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ad Platform Adapter */
            ad_platform_adapter: string;
            /** Ai Provider */
            ai_provider: string;
            /** App Env */
            app_env: string;
            /** Status */
            status: string;
        };
        /**
         * MainConversion
         * @description Основная целевая конверсия проекта (v0.3 §13).
         * @enum {string}
         */
        MainConversion: "lead" | "call" | "message" | "order" | "purchase";
        /**
         * MetricRead
         * @description Значение метрики вместе с оценкой достоверности.
         *
         *     Состояния совпадают с состояниями карточки KPI в интерфейсе: одно и то же
         *     понятие не должно называться по-разному на разных концах системы.
         */
        MetricRead: {
            availability: components["schemas"]["Availability"];
            /**
             * Reason
             * @description Что заполнить, чтобы значение стало достоверным
             */
            reason?: string | null;
            /** Value */
            value: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Primary Region */
            primary_region?: string | null;
            /** Website Url */
            website_url?: string | null;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Total */
            total: number;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Region */
            primary_region: string | null;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Website Url */
            website_url: string | null;
        };
        /**
         * ProjectStatus
         * @description Технический статус проекта.
         *
         *     Намеренно не совпадает один в один с десятишаговым пользовательским
         *     жизненным циклом (v0.4 §3): интерфейс показывает этап работы, база хранит
         *     состояние обработки, и смешивать их не нужно.
         * @enum {string}
         */
        ProjectStatus: "draft" | "active" | "paused" | "archived" | "error";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_economics_api_v1_projects__project_id__economics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_economics_api_v1_projects__project_id__economics_put: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EconomicsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
