/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Возврат после входа через Яндекс */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Начать вход через Яндекс */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние сервиса
         * @description Возвращает состояние и режим работы.
         *
         *     Провайдер AI и адаптер площадки показаны намеренно: по ответу должно быть
         *     сразу видно, работает ли стенд на заглушках. Иначе легко принять
         *     сгенерированный заглушкой результат за вывод настоящей модели.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Моя организация
         * @description Сведения о своей организации.
         *
         *     Идентификатор берётся из контекста, а не из адреса запроса: организация,
         *     которую можно указать параметром, — это готовый способ заглянуть в чужую
         *     (v0.3 §93).
         */
        get: operations["get_organization_api_v1_organization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить участника
         * @description Выдаёт человеку доступ.
         *
         *     Приглашение по почте с одноразовой ссылкой не нужно: личность подтверждает
         *     Яндекс ID. Достаточно записать почту — при входе человек будет опознан по
         *     ней. Пока он не вошёл, запись означает ровно «доступ выдан, но не
         *     использован».
         */
        post: operations["add_member_api_v1_organization_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить участника */
        patch: operations["update_member_api_v1_organization_members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка по проектам */
        get: operations["get_overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список проектов */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Создать проект */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проект */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Удалить проект
         * @description Мягкое удаление (v0.3 §61).
         *
         *     Запись остаётся в базе и перестаёт появляться в выборках. Так удалённый по
         *     ошибке проект можно вернуть, а история аудитов и конкурентов не исчезает
         *     вместе с ним в тот же миг. Окончательное удаление — отдельная процедура по
         *     истечении срока хранения.
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Изменить проект */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последний аудит сайта */
        get: operations["get_audit_api_v1_projects__project_id__audit_get"];
        put?: never;
        /** Запустить аудит сайта */
        post: operations["start_audit_api_v1_projects__project_id__audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История проверок сайта
         * @description История запусков (v0.3 §62).
         *
         *     Отвечает на один вопрос: помогли доработки сайта или нет. Поэтому рядом с
         *     баллом показывается его изменение относительно прошлой завершённой
         *     проверки — само по себе число «74» об этом ничего не говорит.
         */
        get: operations["get_audit_history_api_v1_projects__project_id__audits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сравнение с конкурентами */
        get: operations["get_comparison_api_v1_projects__project_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Конкуренты проекта */
        get: operations["list_competitors_api_v1_projects__project_id__competitors_get"];
        put?: never;
        /** Добавить конкурента */
        post: operations["add_competitor_api_v1_projects__project_id__competitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors/{competitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить конкурента */
        delete: operations["delete_competitor_api_v1_projects__project_id__competitors__competitor_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors/{competitor_id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перепроверить конкурента */
        post: operations["recheck_competitor_api_v1_projects__project_id__competitors__competitor_id__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экономика проекта и производные метрики */
        get: operations["get_economics_api_v1_projects__project_id__economics_get"];
        /** Сохранить экономику проекта */
        put: operations["update_economics_api_v1_projects__project_id__economics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Прогресс проекта по шагам */
        get: operations["get_progress_api_v1_projects__project_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditHistory */
        AuditHistory: {
            /** Items */
            items: components["schemas"]["AuditHistoryItem"][];
            /** Total */
            total: number;
        };
        /**
         * AuditHistoryItem
         * @description Одна прошлая проверка.
         *
         *     Без списка находок: история отвечает на вопрос «стало лучше или хуже», а не
         *     «что именно сломано». За подробностями — в последний результат.
         */
        AuditHistoryItem: {
            /** Can Launch */
            can_launch: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Score */
            score: number | null;
            /** Score Delta */
            score_delta: number | null;
            status: components["schemas"]["ModuleStatus"];
            /** Verdict */
            verdict: string | null;
        };
        /**
         * AuditIssueRead
         * @description Находка аудита.
         *
         *     Поле `action` обязательное: находка без понятного действия бесполезна.
         */
        AuditIssueRead: {
            /** Action */
            action: string;
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
        };
        /** AuditRead */
        AuditRead: {
            /** Can Launch */
            can_launch: boolean;
            /** Categories */
            categories: components["schemas"]["CategoryRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /** Final Url */
            final_url: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issues */
            issues: components["schemas"]["AuditIssueRead"][];
            /** Metrica Counter */
            metrica_counter: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Score */
            score: number | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ModuleStatus"];
            /** Url */
            url: string;
            /** Verdict */
            verdict: string | null;
        };
        /**
         * Availability
         * @description Насколько можно доверять значению.
         *
         *     Совпадает с состояниями карточки KPI в интерфейсе — одно и то же понятие не
         *     должно называться по-разному на разных концах системы.
         * @enum {string}
         */
        Availability: "available" | "proxy" | "unavailable";
        /**
         * CategoryRead
         * @description Оценка по одной категории аудита.
         */
        CategoryRead: {
            /** Category */
            category: string;
            /** Findings */
            findings?: string[];
            /** Score */
            score: number;
        };
        /** ComparisonRead */
        ComparisonRead: {
            /** Own Site Checked */
            own_site_checked: boolean;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Rivals Checked */
            rivals_checked: number;
            /** Rows */
            rows: components["schemas"]["FeatureRowRead"][];
            /** Summary */
            summary: string | null;
        };
        /** CompetitorCreate */
        CompetitorCreate: {
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** CompetitorList */
        CompetitorList: {
            /** Items */
            items: components["schemas"]["CompetitorRead"][];
            /** Total */
            total: number;
        };
        /** CompetitorRead */
        CompetitorRead: {
            /** Checked At */
            checked_at: string | null;
            /** Error Reason */
            error_reason: string | null;
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["ModuleStatus"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /**
         * CurrentUserRead
         * @description Кто вошёл. Ответ на вопрос интерфейса «показывать приложение или вход».
         */
        CurrentUserRead: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            /** Role */
            role: string;
        };
        /**
         * EconomicsMode
         * @description Полнота экономики (v0.4 §5).
         * @enum {string}
         */
        EconomicsMode: "complete" | "limited" | "insufficient";
        /** EconomicsRead */
        EconomicsRead: {
            /** Average Order Value */
            average_order_value: string | null;
            /** Expected Value */
            expected_value: string | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate: string | null;
            main_conversion: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent: string | null;
            /** Monthly Budget */
            monthly_budget: string | null;
            /** Target Cac */
            target_cac: string | null;
            /** Target Cpl */
            target_cpl: string | null;
            /** Target Marketing Share */
            target_marketing_share: string | null;
            /** Version */
            version: number;
        };
        /**
         * EconomicsResponse
         * @description Ответ экономики: введённые данные и производные величины отдельно.
         *
         *     Разделение намеренное — интерфейс обязан отличать данные от вывода системы
         *     (v0.3 §140).
         */
        EconomicsResponse: {
            input: components["schemas"]["EconomicsRead"] | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            summary: components["schemas"]["EconomicsSummaryRead"];
        };
        /** EconomicsSummaryRead */
        EconomicsSummaryRead: {
            break_even_cac: components["schemas"]["MetricRead"];
            break_even_cpl: components["schemas"]["MetricRead"];
            break_even_roas: components["schemas"]["MetricRead"];
            /** Can Optimize By Sales */
            can_optimize_by_sales: boolean;
            /** Cta */
            cta: string | null;
            gross_profit_per_sale: components["schemas"]["MetricRead"];
            /** Missing Recommended */
            missing_recommended: string[];
            /** Missing Required */
            missing_required: string[];
            mode: components["schemas"]["EconomicsMode"];
            monthly_leads_capacity: components["schemas"]["MetricRead"];
            monthly_sales_capacity: components["schemas"]["MetricRead"];
            projected_gross_profit: components["schemas"]["MetricRead"];
            projected_revenue: components["schemas"]["MetricRead"];
            target_cac: components["schemas"]["MetricRead"];
            target_cpl: components["schemas"]["MetricRead"];
            target_roas: components["schemas"]["MetricRead"];
        };
        /**
         * EconomicsUpdate
         * @description Ввод экономики.
         *
         *     Все поля необязательные: проект не блокируется из-за незаполненной экономики
         *     (v0.4 §5). Полнота оценивается расчётом, а не валидацией запроса.
         */
        EconomicsUpdate: {
            /** Average Order Value */
            average_order_value?: number | string | null;
            /** Expected Value */
            expected_value?: number | string | null;
            /** Expected Version */
            expected_version?: number | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate?: number | string | null;
            main_conversion?: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent?: number | string | null;
            /** Monthly Budget */
            monthly_budget?: number | string | null;
            /** Target Cac */
            target_cac?: number | string | null;
            /** Target Cpl */
            target_cpl?: number | string | null;
            /** Target Marketing Share */
            target_marketing_share?: number | string | null;
        };
        /**
         * FeatureKey
         * @description Сравнимые свойства страницы.
         *
         *     Список закрытый и короткий: сравнение по тридцати признакам перестаёт быть
         *     сравнением и становится таблицей, которую никто не читает.
         * @enum {string}
         */
        FeatureKey: "prices" | "form" | "phone" | "messengers" | "cta" | "trust" | "promo" | "mobile" | "analytics";
        /**
         * FeatureRowRead
         * @description Строка таблицы сравнения.
         */
        FeatureRowRead: {
            /** Is Advantage */
            is_advantage: boolean;
            /** Is Gap */
            is_gap: boolean;
            key: components["schemas"]["FeatureKey"];
            /** Label */
            label: string;
            /** Mine */
            mine: boolean;
            /** Rivals Total */
            rivals_total: number;
            /** Rivals With */
            rivals_with: number;
            /** Why */
            why: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ad Platform Adapter */
            ad_platform_adapter: string;
            /** Ai Provider */
            ai_provider: string;
            /** App Env */
            app_env: string;
            /** Status */
            status: string;
        };
        /**
         * MainConversion
         * @description Основная целевая конверсия проекта (v0.3 §13).
         * @enum {string}
         */
        MainConversion: "lead" | "call" | "message" | "order" | "purchase";
        /**
         * MemberCreate
         * @description Добавление участника.
         *
         *     Пароля здесь нет и быть не может: вход идёт через Яндекс ID. Достаточно
         *     почты — по ней человек и будет опознан при входе.
         */
        MemberCreate: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @default specialist
             * @enum {string}
             */
            role: "owner" | "specialist" | "viewer";
        };
        /**
         * MemberRead
         * @description Участник организации.
         *
         *     Пароля и способов входа здесь нет: аутентификация появится отдельным срезом
         *     вместе с MFA (v0.3 §91).
         */
        MemberRead: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Has Logged In */
            has_logged_in: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Role */
            role: string;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Role */
            role?: ("owner" | "specialist" | "viewer") | null;
        };
        /**
         * MetricRead
         * @description Значение метрики вместе с оценкой достоверности.
         *
         *     Состояния совпадают с состояниями карточки KPI в интерфейсе: одно и то же
         *     понятие не должно называться по-разному на разных концах системы.
         */
        MetricRead: {
            availability: components["schemas"]["Availability"];
            /**
             * Reason
             * @description Что заполнить, чтобы значение стало достоверным
             */
            reason?: string | null;
            /** Value */
            value: string | null;
        };
        /**
         * ModuleStatus
         * @description Состояние работы модуля (v0.3 §5).
         *
         *     Общее для всех долгих операций: аудита, сбора семантики, анализа
         *     конкурентов. Интерфейс показывает их одинаково, поэтому и в базе они
         *     называются одинаково.
         * @enum {string}
         */
        ModuleStatus: "not_started" | "queued" | "running" | "needs_review" | "completed" | "failed";
        /** OrganizationRead */
        OrganizationRead: {
            /** Ad Platform Adapter */
            ad_platform_adapter: string;
            /** Ai Provider */
            ai_provider: string;
            /** App Env */
            app_env: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Members */
            members: components["schemas"]["MemberRead"][];
            /** Name */
            name: string;
            plan: components["schemas"]["PlanRead"] | null;
            /** Projects Count */
            projects_count: number;
            /** Slug */
            slug: string;
        };
        /**
         * OverviewRead
         * @description Сводка по всем проектам.
         *
         *     Намеренно не содержит расходов, лидов и продаж: рекламный кабинет не
         *     подключён, и любые цифры здесь были бы выдуманными. Поле
         *     `ad_platform_connected` существует ровно для того, чтобы интерфейс сказал
         *     об этом прямо, а не рисовал нули (v0.3 §140).
         */
        OverviewRead: {
            /** Ad Platform Connected */
            ad_platform_connected: boolean;
            /** Needs Attention */
            needs_attention: number;
            /** Projects */
            projects: components["schemas"]["ProjectSummaryRead"][];
            /** Total */
            total: number;
        };
        /**
         * PlanRead
         * @description Лимиты организации (v0.4 §13).
         *
         *     Платёжная система в MVP не подключается, но потолки существуют с первого
         *     дня — иначе их некуда будет добавить, когда появится биллинг.
         */
        PlanRead: {
            /** Ai Usage Limit */
            ai_usage_limit: number;
            /** Crawler Pages Limit */
            crawler_pages_limit: number;
            /** Max Projects */
            max_projects: number;
            /** Max Users */
            max_users: number;
            /** Retention Days */
            retention_days: number;
        };
        /**
         * ProgressRead
         * @description Где находится проект и что делать дальше.
         *
         *     Считается на сервере, а не в интерфейсе: то же самое понадобится боту, и
         *     два независимых расчёта неизбежно разошлись бы.
         */
        ProgressRead: {
            /** Completed Count */
            completed_count: number;
            current: components["schemas"]["StepKey"];
            /** Next Action */
            next_action: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Steps */
            steps: components["schemas"]["StepRead"][];
            /** Total Count */
            total_count: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Primary Region */
            primary_region?: string | null;
            /** Website Url */
            website_url?: string | null;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Total */
            total: number;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Region */
            primary_region: string | null;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Website Url */
            website_url: string | null;
        };
        /**
         * ProjectStatus
         * @description Технический статус проекта.
         *
         *     Намеренно не совпадает один в один с десятишаговым пользовательским
         *     жизненным циклом (v0.4 §3): интерфейс показывает этап работы, база хранит
         *     состояние обработки, и смешивать их не нужно.
         * @enum {string}
         */
        ProjectStatus: "draft" | "active" | "paused" | "archived" | "error";
        /**
         * ProjectSummaryRead
         * @description Строка проекта на главном экране.
         *
         *     Собирается на сервере одним запросом на все проекты. Собирать её в браузере
         *     значило бы дёргать по четыре запроса на каждый проект — и показывать
         *     страницу, которая тем медленнее, чем больше клиентов у агентства.
         */
        ProjectSummaryRead: {
            /** Audit Score */
            audit_score: number | null;
            audit_status: components["schemas"]["ModuleStatus"] | null;
            /** Can Launch */
            can_launch: boolean;
            /** Competitors Checked */
            competitors_checked: number;
            /** Completed Count */
            completed_count: number;
            current_step: components["schemas"]["StepKey"];
            /** Current Step Label */
            current_step_label: string;
            economics_mode: components["schemas"]["EconomicsMode"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Next Action */
            next_action: string | null;
            status: components["schemas"]["ProjectStatus"];
            /** Total Count */
            total_count: number;
            /** Website Url */
            website_url: string | null;
        };
        /**
         * ProjectUpdate
         * @description Изменение проекта.
         *
         *     Все поля необязательные: приходит только то, что меняют. Отличить
         *     «не передано» от «очищено» позволяет `exclude_unset` при разборе.
         */
        ProjectUpdate: {
            /** Expected Version */
            expected_version?: number | null;
            /** Name */
            name?: string | null;
            /** Primary Region */
            primary_region?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Website Url */
            website_url?: string | null;
        };
        /**
         * StepKey
         * @description Ключи шагов. Порядок объявления — это и есть порядок работы.
         * @enum {string}
         */
        StepKey: "onboarding" | "research" | "economics" | "strategy" | "build" | "validate" | "launch" | "measure" | "optimize" | "scale";
        /**
         * StepRead
         * @description Шаг канонического жизненного цикла (v0.4 §3).
         */
        StepRead: {
            /** Hint */
            hint?: string | null;
            key: components["schemas"]["StepKey"];
            /** Label */
            label: string;
            state: components["schemas"]["StepState"];
        };
        /**
         * StepState
         * @description Состояние шага. Совпадает с состояниями компонента WorkflowStepper.
         * @enum {string}
         */
        StepState: "completed" | "active" | "waiting" | "blocked" | "error";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_api_v1_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_organization_api_v1_organization_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_organization_members_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_organization_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_v1_projects__project_id__audit_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_audit_api_v1_projects__project_id__audit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_history_api_v1_projects__project_id__audits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_v1_projects__project_id__comparison_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_competitors_api_v1_projects__project_id__competitors_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_competitor_api_v1_projects__project_id__competitors_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_competitor_api_v1_projects__project_id__competitors__competitor_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
                competitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recheck_competitor_api_v1_projects__project_id__competitors__competitor_id__recheck_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
                competitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_economics_api_v1_projects__project_id__economics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_economics_api_v1_projects__project_id__economics_put: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EconomicsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_v1_projects__project_id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
