/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние сервиса
         * @description Возвращает состояние и режим работы.
         *
         *     Провайдер AI и адаптер площадки показаны намеренно: по ответу должно быть
         *     сразу видно, работает ли стенд на заглушках. Иначе легко принять
         *     сгенерированный заглушкой результат за вывод настоящей модели.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список проектов */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Создать проект */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проект */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить проект */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последний аудит сайта */
        get: operations["get_audit_api_v1_projects__project_id__audit_get"];
        put?: never;
        /** Запустить аудит сайта */
        post: operations["start_audit_api_v1_projects__project_id__audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сравнение с конкурентами */
        get: operations["get_comparison_api_v1_projects__project_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Конкуренты проекта */
        get: operations["list_competitors_api_v1_projects__project_id__competitors_get"];
        put?: never;
        /** Добавить конкурента */
        post: operations["add_competitor_api_v1_projects__project_id__competitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors/{competitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить конкурента */
        delete: operations["delete_competitor_api_v1_projects__project_id__competitors__competitor_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/competitors/{competitor_id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перепроверить конкурента */
        post: operations["recheck_competitor_api_v1_projects__project_id__competitors__competitor_id__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экономика проекта и производные метрики */
        get: operations["get_economics_api_v1_projects__project_id__economics_get"];
        /** Сохранить экономику проекта */
        put: operations["update_economics_api_v1_projects__project_id__economics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Прогресс проекта по шагам */
        get: operations["get_progress_api_v1_projects__project_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditIssueRead
         * @description Находка аудита.
         *
         *     Поле `action` обязательное: находка без понятного действия бесполезна.
         */
        AuditIssueRead: {
            /** Action */
            action: string;
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
        };
        /** AuditRead */
        AuditRead: {
            /** Can Launch */
            can_launch: boolean;
            /** Categories */
            categories: components["schemas"]["CategoryRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /** Final Url */
            final_url: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issues */
            issues: components["schemas"]["AuditIssueRead"][];
            /** Metrica Counter */
            metrica_counter: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Score */
            score: number | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ModuleStatus"];
            /** Url */
            url: string;
            /** Verdict */
            verdict: string | null;
        };
        /**
         * Availability
         * @description Насколько можно доверять значению.
         *
         *     Совпадает с состояниями карточки KPI в интерфейсе — одно и то же понятие не
         *     должно называться по-разному на разных концах системы.
         * @enum {string}
         */
        Availability: "available" | "proxy" | "unavailable";
        /**
         * CategoryRead
         * @description Оценка по одной категории аудита.
         */
        CategoryRead: {
            /** Category */
            category: string;
            /** Findings */
            findings?: string[];
            /** Score */
            score: number;
        };
        /** ComparisonRead */
        ComparisonRead: {
            /** Own Site Checked */
            own_site_checked: boolean;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Rivals Checked */
            rivals_checked: number;
            /** Rows */
            rows: components["schemas"]["FeatureRowRead"][];
            /** Summary */
            summary: string | null;
        };
        /** CompetitorCreate */
        CompetitorCreate: {
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** CompetitorList */
        CompetitorList: {
            /** Items */
            items: components["schemas"]["CompetitorRead"][];
            /** Total */
            total: number;
        };
        /** CompetitorRead */
        CompetitorRead: {
            /** Checked At */
            checked_at: string | null;
            /** Error Reason */
            error_reason: string | null;
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["ModuleStatus"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /**
         * EconomicsMode
         * @description Полнота экономики (v0.4 §5).
         * @enum {string}
         */
        EconomicsMode: "complete" | "limited" | "insufficient";
        /** EconomicsRead */
        EconomicsRead: {
            /** Average Order Value */
            average_order_value: string | null;
            /** Expected Value */
            expected_value: string | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate: string | null;
            main_conversion: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent: string | null;
            /** Monthly Budget */
            monthly_budget: string | null;
            /** Target Cac */
            target_cac: string | null;
            /** Target Cpl */
            target_cpl: string | null;
            /** Target Marketing Share */
            target_marketing_share: string | null;
            /** Version */
            version: number;
        };
        /**
         * EconomicsResponse
         * @description Ответ экономики: введённые данные и производные величины отдельно.
         *
         *     Разделение намеренное — интерфейс обязан отличать данные от вывода системы
         *     (v0.3 §140).
         */
        EconomicsResponse: {
            input: components["schemas"]["EconomicsRead"] | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            summary: components["schemas"]["EconomicsSummaryRead"];
        };
        /** EconomicsSummaryRead */
        EconomicsSummaryRead: {
            break_even_cac: components["schemas"]["MetricRead"];
            break_even_cpl: components["schemas"]["MetricRead"];
            break_even_roas: components["schemas"]["MetricRead"];
            /** Can Optimize By Sales */
            can_optimize_by_sales: boolean;
            /** Cta */
            cta: string | null;
            gross_profit_per_sale: components["schemas"]["MetricRead"];
            /** Missing Recommended */
            missing_recommended: string[];
            /** Missing Required */
            missing_required: string[];
            mode: components["schemas"]["EconomicsMode"];
            monthly_leads_capacity: components["schemas"]["MetricRead"];
            monthly_sales_capacity: components["schemas"]["MetricRead"];
            projected_gross_profit: components["schemas"]["MetricRead"];
            projected_revenue: components["schemas"]["MetricRead"];
            target_cac: components["schemas"]["MetricRead"];
            target_cpl: components["schemas"]["MetricRead"];
            target_roas: components["schemas"]["MetricRead"];
        };
        /**
         * EconomicsUpdate
         * @description Ввод экономики.
         *
         *     Все поля необязательные: проект не блокируется из-за незаполненной экономики
         *     (v0.4 §5). Полнота оценивается расчётом, а не валидацией запроса.
         */
        EconomicsUpdate: {
            /** Average Order Value */
            average_order_value?: number | string | null;
            /** Expected Value */
            expected_value?: number | string | null;
            /** Expected Version */
            expected_version?: number | null;
            /** Lead To Sale Rate */
            lead_to_sale_rate?: number | string | null;
            main_conversion?: components["schemas"]["MainConversion"] | null;
            /** Margin Percent */
            margin_percent?: number | string | null;
            /** Monthly Budget */
            monthly_budget?: number | string | null;
            /** Target Cac */
            target_cac?: number | string | null;
            /** Target Cpl */
            target_cpl?: number | string | null;
            /** Target Marketing Share */
            target_marketing_share?: number | string | null;
        };
        /**
         * FeatureKey
         * @description Сравнимые свойства страницы.
         *
         *     Список закрытый и короткий: сравнение по тридцати признакам перестаёт быть
         *     сравнением и становится таблицей, которую никто не читает.
         * @enum {string}
         */
        FeatureKey: "prices" | "form" | "phone" | "messengers" | "cta" | "trust" | "promo" | "mobile" | "analytics";
        /**
         * FeatureRowRead
         * @description Строка таблицы сравнения.
         */
        FeatureRowRead: {
            /** Is Advantage */
            is_advantage: boolean;
            /** Is Gap */
            is_gap: boolean;
            key: components["schemas"]["FeatureKey"];
            /** Label */
            label: string;
            /** Mine */
            mine: boolean;
            /** Rivals Total */
            rivals_total: number;
            /** Rivals With */
            rivals_with: number;
            /** Why */
            why: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ad Platform Adapter */
            ad_platform_adapter: string;
            /** Ai Provider */
            ai_provider: string;
            /** App Env */
            app_env: string;
            /** Status */
            status: string;
        };
        /**
         * MainConversion
         * @description Основная целевая конверсия проекта (v0.3 §13).
         * @enum {string}
         */
        MainConversion: "lead" | "call" | "message" | "order" | "purchase";
        /**
         * MetricRead
         * @description Значение метрики вместе с оценкой достоверности.
         *
         *     Состояния совпадают с состояниями карточки KPI в интерфейсе: одно и то же
         *     понятие не должно называться по-разному на разных концах системы.
         */
        MetricRead: {
            availability: components["schemas"]["Availability"];
            /**
             * Reason
             * @description Что заполнить, чтобы значение стало достоверным
             */
            reason?: string | null;
            /** Value */
            value: string | null;
        };
        /**
         * ModuleStatus
         * @description Состояние работы модуля (v0.3 §5).
         *
         *     Общее для всех долгих операций: аудита, сбора семантики, анализа
         *     конкурентов. Интерфейс показывает их одинаково, поэтому и в базе они
         *     называются одинаково.
         * @enum {string}
         */
        ModuleStatus: "not_started" | "queued" | "running" | "needs_review" | "completed" | "failed";
        /**
         * ProgressRead
         * @description Где находится проект и что делать дальше.
         *
         *     Считается на сервере, а не в интерфейсе: то же самое понадобится боту, и
         *     два независимых расчёта неизбежно разошлись бы.
         */
        ProgressRead: {
            /** Completed Count */
            completed_count: number;
            current: components["schemas"]["StepKey"];
            /** Next Action */
            next_action: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Steps */
            steps: components["schemas"]["StepRead"][];
            /** Total Count */
            total_count: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Primary Region */
            primary_region?: string | null;
            /** Website Url */
            website_url?: string | null;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Total */
            total: number;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Region */
            primary_region: string | null;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Website Url */
            website_url: string | null;
        };
        /**
         * ProjectStatus
         * @description Технический статус проекта.
         *
         *     Намеренно не совпадает один в один с десятишаговым пользовательским
         *     жизненным циклом (v0.4 §3): интерфейс показывает этап работы, база хранит
         *     состояние обработки, и смешивать их не нужно.
         * @enum {string}
         */
        ProjectStatus: "draft" | "active" | "paused" | "archived" | "error";
        /**
         * ProjectUpdate
         * @description Изменение проекта.
         *
         *     Все поля необязательные: приходит только то, что меняют. Отличить
         *     «не передано» от «очищено» позволяет `exclude_unset` при разборе.
         */
        ProjectUpdate: {
            /** Expected Version */
            expected_version?: number | null;
            /** Name */
            name?: string | null;
            /** Primary Region */
            primary_region?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Website Url */
            website_url?: string | null;
        };
        /**
         * StepKey
         * @description Ключи шагов. Порядок объявления — это и есть порядок работы.
         * @enum {string}
         */
        StepKey: "onboarding" | "research" | "economics" | "strategy" | "build" | "validate" | "launch" | "measure" | "optimize" | "scale";
        /**
         * StepRead
         * @description Шаг канонического жизненного цикла (v0.4 §3).
         */
        StepRead: {
            /** Hint */
            hint?: string | null;
            key: components["schemas"]["StepKey"];
            /** Label */
            label: string;
            state: components["schemas"]["StepState"];
        };
        /**
         * StepState
         * @description Состояние шага. Совпадает с состояниями компонента WorkflowStepper.
         * @enum {string}
         */
        StepState: "completed" | "active" | "waiting" | "blocked" | "error";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_v1_projects__project_id__audit_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_audit_api_v1_projects__project_id__audit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_v1_projects__project_id__comparison_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_competitors_api_v1_projects__project_id__competitors_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_competitor_api_v1_projects__project_id__competitors_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_competitor_api_v1_projects__project_id__competitors__competitor_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
                competitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recheck_competitor_api_v1_projects__project_id__competitors__competitor_id__recheck_post: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
                competitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_economics_api_v1_projects__project_id__economics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_economics_api_v1_projects__project_id__economics_put: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EconomicsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_v1_projects__project_id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                "x-organization-id"?: string | null;
                "x-user-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
