"""фрагменты предложения

Revision ID: 08d81148f8c4
Revises: 23ef63b8054f
Create Date: 2026-08-15 22:14:29.437173
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '08d81148f8c4'
down_revision: str | None = '23ef63b8054f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Значение по умолчанию обязательно: колонка NOT NULL, а проверки в таблице
    # уже есть, и без него миграция упала бы на первой же существующей записи.
    # У старых проверок фрагментов нет — там честно пустой список, а не выдумка.
    op.add_column(
        'site_audits',
        sa.Column(
            'selling_points',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
    )
    op.alter_column('site_audits', 'selling_points', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'selling_points')
    # ### end Alembic commands ###
