"""анкета клиента с сайта

Revision ID: 09f3aef77574
Revises: 11f51505efc5
Create Date: 2026-08-17 20:36:59.979079
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '09f3aef77574'
down_revision: str | None = '11f51505efc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Значение по умолчанию обязательно: столбец не допускает пустоты, а в
    # таблице уже лежат проверки, сделанные до появления анкеты. Без него
    # обновление падает прямо на боевой базе — там, где проверок больше всего.
    #
    # После заполнения умолчание снимается: значение подставляет приложение, и
    # оставленное на уровне базы однажды разойдётся с ним.
    op.add_column(
        'site_audits',
        sa.Column(
            'client_profile',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('site_audits', 'client_profile', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'client_profile')
    # ### end Alembic commands ###
