"""Project Data Core

Revision ID: 0d93a4d169c1
Revises: 
Create Date: 2026-08-15 15:30:12.712831
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0d93a4d169c1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_table('organization_plans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('ai_usage_limit', sa.Integer(), nullable=False),
    sa.Column('crawler_pages_limit', sa.Integer(), nullable=False),
    sa.Column('semantic_requests_limit', sa.Integer(), nullable=False),
    sa.Column('report_limit', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('autopilot_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_plans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_plans')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_plans_organization_id'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'SPECIALIST', 'VIEWER', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='organization_id_email')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_region', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'ERROR', name='project_status', native_enum=False, length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('project_economics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('main_conversion', sa.Enum('LEAD', 'CALL', 'MESSAGE', 'ORDER', 'PURCHASE', name='main_conversion', native_enum=False, length=20), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_to_sale_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('target_cac', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_cpl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_marketing_share', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_economics_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_economics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_economics')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_economics_project_id'))
    )
    op.create_index(op.f('ix_project_economics_organization_id'), 'project_economics', ['organization_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.Enum('AI', 'CRAWLER', 'EXTERNAL_API', 'STORAGE', 'REPORT', name='usage_service', native_enum=False, length=20), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit', sa.Enum('TOKENS', 'REQUESTS', 'PAGES', 'BYTES', name='usage_unit', native_enum=False, length=20), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_usage_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_usage_events_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index('ix_usage_events_org_created', 'usage_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_organization_id'), 'usage_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_organization_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_org_created', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_project_economics_organization_id'), table_name='project_economics')
    op.drop_table('project_economics')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('organization_plans')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
