"""бриф для сбора запросов

Revision ID: 11f51505efc5
Revises: 6b87b9059524
Create Date: 2026-08-17 18:55:21.283032
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '11f51505efc5'
down_revision: str | None = '6b87b9059524'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_briefs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sells', sa.Text(), nullable=False),
    sa.Column('synonyms', sa.Text(), nullable=False),
    sa.Column('excludes', sa.Text(), nullable=False),
    sa.Column('cities', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_briefs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keyword_briefs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_briefs'))
    )
    op.create_index(op.f('ix_keyword_briefs_organization_id'), 'keyword_briefs', ['organization_id'], unique=False)
    op.create_index('uq_keyword_brief_project', 'keyword_briefs', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_keyword_brief_project', table_name='keyword_briefs')
    op.drop_index(op.f('ix_keyword_briefs_organization_id'), table_name='keyword_briefs')
    op.drop_table('keyword_briefs')
    # ### end Alembic commands ###
