"""наборы минус-слов

Revision ID: 1cb54e350bce
Revises: 91597ac50c73
Create Date: 2026-08-15 22:58:29.029758
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '1cb54e350bce'
down_revision: str | None = '91597ac50c73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minus_word_sets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_minus_word_sets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_minus_word_sets_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minus_word_sets'))
    )
    op.create_index(op.f('ix_minus_word_sets_organization_id'), 'minus_word_sets', ['organization_id'], unique=False)
    op.create_index('uq_minus_word_set_name', 'minus_word_sets', ['organization_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_minus_word_set_name', table_name='minus_word_sets')
    op.drop_index(op.f('ix_minus_word_sets_organization_id'), table_name='minus_word_sets')
    op.drop_table('minus_word_sets')
    # ### end Alembic commands ###
