"""семантическое ядро

Revision ID: 23ef63b8054f
Revises: f0a734c421d3
Create Date: 2026-08-15 21:58:18.672610
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '23ef63b8054f'
down_revision: str | None = 'f0a734c421d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.String(length=400), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('intent', sa.Enum('COMMERCIAL', 'INFORMATIONAL', 'IRRELEVANT', name='keyword_intent', native_enum=False, length=20), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('cluster_name', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keywords_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords'))
    )
    op.create_index('ix_keyword_project_intent', 'keywords', ['project_id', 'intent'], unique=False)
    op.create_index(op.f('ix_keywords_organization_id'), 'keywords', ['organization_id'], unique=False)
    op.create_index('uq_keyword_phrase', 'keywords', ['project_id', 'phrase'], unique=True)
    op.create_table('minus_words',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_minus_words_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_minus_words_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minus_words'))
    )
    op.create_index(op.f('ix_minus_words_organization_id'), 'minus_words', ['organization_id'], unique=False)
    op.create_index('uq_minus_word', 'minus_words', ['project_id', 'word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_minus_word', table_name='minus_words')
    op.drop_index(op.f('ix_minus_words_organization_id'), table_name='minus_words')
    op.drop_table('minus_words')
    op.drop_index('uq_keyword_phrase', table_name='keywords')
    op.drop_index(op.f('ix_keywords_organization_id'), table_name='keywords')
    op.drop_index('ix_keyword_project_intent', table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
