"""условия предложения

Revision ID: 60ae413ce782
Revises: 09f3aef77574
Create Date: 2026-08-17 20:47:58.817721
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '60ae413ce782'
down_revision: str | None = '09f3aef77574'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Значение по умолчанию обязательно: столбцы не допускают пустоты, а в
    # таблицах уже лежат разборы, сделанные до появления условий. Без него
    # обновление падает на боевой базе — там, где записей больше всего.
    #
    # После заполнения умолчание снимается: значение подставляет приложение.
    op.add_column('competitors', sa.Column('offer', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        server_default=sa.text("'{}'::jsonb")))
    op.add_column('site_audits', sa.Column('offer', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        server_default=sa.text("'{}'::jsonb")))
    op.alter_column('competitors', 'offer', server_default=None)
    op.alter_column('site_audits', 'offer', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'offer')
    op.drop_column('competitors', 'offer')
    # ### end Alembic commands ###
