"""журнал действий

Revision ID: 86b4bf49f550
Revises: 9c27beeb438f
Create Date: 2026-08-15 21:09:58.674063
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '86b4bf49f550'
down_revision: str | None = '9c27beeb438f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.Enum('PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'ECONOMICS_UPDATED', 'AUDIT_STARTED', 'COMPETITOR_ADDED', 'COMPETITOR_REMOVED', 'MEMBER_ADDED', 'MEMBER_UPDATED', name='activity_action', native_enum=False, length=40), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_activity_log_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_activity_log_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index('ix_activity_log_org_created', 'activity_log', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_log_organization_id'), 'activity_log', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_log_organization_id'), table_name='activity_log')
    op.drop_index('ix_activity_log_org_created', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
