"""внутренние ссылки

Revision ID: 91597ac50c73
Revises: c8d56e6e72d4
Create Date: 2026-08-15 22:54:39.375945
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '91597ac50c73'
down_revision: str | None = 'c8d56e6e72d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Значение по умолчанию обязательно: колонка NOT NULL, а проверки в таблице
    # уже есть. У старых проверок ссылок нет — там честно пустой список.
    op.add_column(
        'site_audits',
        sa.Column(
            'internal_links',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
    )
    op.alter_column('site_audits', 'internal_links', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'internal_links')
    # ### end Alembic commands ###
