"""ответы на вопросы клиенту

Revision ID: 9c11ea989e11
Revises: 60ae413ce782
Create Date: 2026-08-18 08:43:57.278001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '9c11ea989e11'
down_revision: str | None = '60ae413ce782'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Значение по умолчанию обязательно: столбец не допускает пустоты, а
    # брифы в таблице уже есть. После заполнения умолчание снимается —
    # значение подставляет приложение, и оставленное в базе однажды с ним
    # разойдётся.
    op.add_column('keyword_briefs', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        server_default=sa.text("'{}'::jsonb")))
    op.alter_column('keyword_briefs', 'answers', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_briefs', 'answers')
    # ### end Alembic commands ###
