"""уведомления

Revision ID: c8d56e6e72d4
Revises: 08d81148f8c4
Create Date: 2026-08-15 22:24:30.259216
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c8d56e6e72d4'
down_revision: str | None = '08d81148f8c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('SITE_BROKEN', 'SITE_DEGRADED', 'SITE_UNREACHABLE', name='notification_kind', native_enum=False, length=40), nullable=False),
    sa.Column('level', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='notification_level', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=600), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notifications_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notification_dedup', 'notifications', ['project_id', 'dedup_key', 'is_read'], unique=False)
    op.create_index('ix_notification_org_created', 'notifications', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index('ix_notification_org_created', table_name='notifications')
    op.drop_index('ix_notification_dedup', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
