"""признаки страницы в аудите

Revision ID: e32cf33fa460
Revises: 40c6ce75f5fe
Create Date: 2026-08-15 17:03:16.224292
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'e32cf33fa460'
down_revision: str | None = '40c6ce75f5fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Значение по умолчанию задаётся на стороне базы: без него добавление
    # NOT NULL-колонки упало бы на таблице с уже накопленными аудитами.
    op.add_column(
        'site_audits',
        sa.Column(
            'features',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'features')
    # ### end Alembic commands ###
