"""скрытые замечания

Revision ID: f0a734c421d3
Revises: 86b4bf49f550
Create Date: 2026-08-15 21:45:05.070814
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f0a734c421d3'
down_revision: str | None = '86b4bf49f550'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_dismissals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issue_key', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('dismissed_by_id', sa.UUID(), nullable=True),
    sa.Column('dismissed_by_name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], name=op.f('fk_issue_dismissals_dismissed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_issue_dismissals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_issue_dismissals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_dismissals'))
    )
    op.create_index(op.f('ix_issue_dismissals_organization_id'), 'issue_dismissals', ['organization_id'], unique=False)
    op.create_index('uq_issue_dismissal', 'issue_dismissals', ['project_id', 'issue_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_issue_dismissal', table_name='issue_dismissals')
    op.drop_index(op.f('ix_issue_dismissals_organization_id'), table_name='issue_dismissals')
    op.drop_table('issue_dismissals')
    # ### end Alembic commands ###
