"""Аудит сайта

Revision ID: f85905b1198b
Revises: 0d93a4d169c1
Create Date: 2026-08-15 16:26:23.098907
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'f85905b1198b'
down_revision: str | None = '0d93a4d169c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_audits',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'QUEUED', 'RUNNING', 'NEEDS_REVIEW', 'COMPLETED', 'FAILED', name='module_status', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrica_counter', sa.String(length=20), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('error_reason', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_site_audits_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_site_audits_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_audits'))
    )
    op.create_index(op.f('ix_site_audits_organization_id'), 'site_audits', ['organization_id'], unique=False)
    op.create_index('ix_site_audits_project_created', 'site_audits', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_audits_project_created', table_name='site_audits')
    op.drop_index(op.f('ix_site_audits_organization_id'), table_name='site_audits')
    op.drop_table('site_audits')
    # ### end Alembic commands ###
