"""заголовок страницы

Revision ID: fe5f0a5313c8
Revises: 1cb54e350bce
Create Date: 2026-08-15 23:16:44.024822
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fe5f0a5313c8'
down_revision: str | None = '1cb54e350bce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_audits', sa.Column('page_title', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'page_title')
    # ### end Alembic commands ###
